zero:
  - type: joint
    joint: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    vel: 0.2
    acc: 0.2

read_pose:
  - type: read_pose

read_joint:
  - type: read_joint

inital_pose:
  - type: joint
    joint: [0.0146, -0.8601, 0.9053, -0.0023, -0.0107, -0.1043]
    vel: 0.2
    acc: 0.2

close_test:
  - type: close_gripper
  - type: delay
    duration: 0.3

open_test:
  - type: open_gripper
  - type: delay
    duration: 0.3

test_ready:
  - type: joint
    joint: [0.0, -0.8, 0.9, 0.0, 0.3, 0.0]
    vel: 0.2
    acc: 0.2

test_x:
  - type: linear
    dir: [1.0, 0.0, 0.0]
    distance: 0.03
    frame: base
    vel: 0.05

test_y:
  - type: linear
    dir: [0.0, 1.0, 0.0]
    distance: 0.03
    frame: base
    vel: 0.05

test_z:
  - type: linear
    dir: [0.0, 0.0, 1.0]
    distance: 0.2
    frame: base
    vel: 0.05

storage_lf:
  - type: trajectory
    file: /home/ws/src/bringup/config/trajectories/LF_Rising.csv
    vel: 0.5
    acc: 0.5
  - type: close_gripper
    duration: 2.0
  - type: trajectory
    file: /home/ws/src/bringup/config/trajectories/LF_PICK.csv
    vel: 0.5
    acc: 0.5
