rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Engineer -> engineer_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmController -> arm_controller
      - rmcs_core::controller::arm::ArmSolver -> arm_solver
      # - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      # - rmcs_core::controller::chassis::OmniWheelController -> omni_wheel_controller
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster
      - rmcs_core::controller::diagnosis::Diagnosis -> diagnosis

value_broadcaster:
  ros__parameters:
    forward_list:
      - /arm/joint_1/motor/angle
      - /arm/joint_2/motor/angle
      - /arm/joint_3/motor/angle
      - /arm/joint_4/motor/angle
      - /arm/joint_5/motor/angle
      - /arm/joint_6/motor/angle
      - /arm/joint_1/motor/raw_angle
      - /arm/joint_2/motor/raw_angle
      - /arm/joint_3/motor/raw_angle
      - /arm/joint_4/motor/raw_angle
      - /arm/joint_5/motor/raw_angle
      - /arm/joint_6/motor/raw_angle
      - /arm/joint_1/motor/velocity
      - /arm/joint_2/motor/velocity
      - /arm/joint_3/motor/velocity
      - /arm/joint_4/motor/velocity
      - /arm/joint_5/motor/velocity
      - /arm/joint_6/motor/velocity
      - /arm/joint_1/motor/control_torque
      - /arm/joint_2/motor/control_torque
      - /arm/joint_3/motor/control_torque
      - /arm/joint_4/motor/control_torque
      - /arm/joint_5/motor/control_torque
      - /arm/joint_6/motor/control_torque
      - /gripper/motor/angle
      - /gripper/motor/control_torque
      - /arm/joint_1/target_velocity
      - /arm/joint_2/target_velocity
      - /arm/joint_3/target_velocity
      - /arm/joint_4/target_velocity
      - /arm/joint_5/target_velocity
      - /arm/joint_6/target_velocity
      - /vt03/trigger
      - /arm/config/reference_latched

engineer_hardware:
  ros__parameters:
    usb_pid_arm_board: 0xa513
    # usb_pid_chassis_board: 0xf112
    arm_joint1_motor_zero_point: 29682
    arm_joint2_motor_zero_point: 54083
    arm_joint3_motor_zero_point: 35846
    arm_joint4_motor_zero_point: 31294
    arm_joint5_motor_zero_point: 32801
    arm_joint6_motor_zero_point: 30864
    gripper_motor_zero_point: 0

arm_config:
  ros__parameters:
    offsets_verified: true
    default_joint_offsets: [8.657788, 1.357540, -1.436022, 7.362341, 8.173817, 1.554690]
    require_latch: false
    latch_joints: [2, 3]
    latch_reference_angle_j2: -1.3265
    latch_reference_angle_j3: 1.3265
    latch_velocity_threshold: 0.1      
    joint_gear_ratio: [1.0, 50.0, 50.0, 1.0, 1.0, 1.0]

arm_controller:
  ros__parameters:
    actions_file: "/home/ws/src/bringup/config/arm_actions.yaml"

arm_solver:
  ros__parameters:
    controller_list: ["gravity","friction","pid"]

# chassis_controller:
#   ros__parameters:
#     translational_velocity_limit: 10.0
#     angular_velocity_limit: 10.0

# omni_wheel_controller:
#   ros__parameters:
#     chassis_radius_x: 0.164
#     chassis_radius_y: 0.162
#     wheel_radius_: 0.077
#     friction_coefficient: 0.3

#     spinning_bais_coefficient: -0.05

diagnosis:
  ros__parameters:
    motors:
      - /arm/joint_1/motor
      - /arm/joint_2/motor
      - /arm/joint_3/motor
      - /arm/joint_4/motor
      - /arm/joint_5/motor
      - /arm/joint_6/motor

    enable_motor_check: true
